#!/usr/bin/env bash

eval $(minishift oc-env)
oc login -u developer
# Create Projects
echo "Creating DEV namespace ..."
oc new-project dev --display-name="Dev Environment" && \
echo "Creating STAGE namespace ..."
oc new-project stage --display-name="Stage environment" && \
echo "Creating CI/CD namespace ..."
oc new-project cicd --display-name="CI/CD Management"

# Grant Jenkins Access to Projects
echo "Adding roles to admin user ..."
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n dev
oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n stage