#!/usr/bin/env bash

eval $(minishift oc-env)
oc login -u developer
# Download ci-cd template and create app from it
oc new-app -n cicd -f https://raw.githubusercontent.com/OpenShiftDemos/openshift-cd-demo/ocp-3.7/cicd-template.yaml