#!/usr/bin/env bash

eval $(minishift oc-env)
oc login -u developer

echo "Import template to recreate deployment config..."
oc create -f ../templates/recreate-example.yaml
echo "Trigger a new deployment by tagging a newer version..."
oc tag recreate-example:v2 recreate-example:latest
echo "Deploying recreate-example"
oc deploy recreate-example