#!/usr/bin/env bash

eval $(minishift oc-env)
oc login -u developer

oc policy add-role-to-user edit system:serviceaccount:dev:default -n dev

#oc project dev
oc new-app -n dev -f ./templates/app-install-template.yaml
